### ISSUE TITLE
/Offernew with response 200 and error

### ISSUE THREAD

**Issue by nlbi21** [syscoin/syscoin-api#6]
Hello guys I was testing the API and when I post a new offer it responds that everything is fine with 200, but then it shows me this error:

> "Error: SYSCOIN_OFFER_RPC_ERROR ERRCODE: 1503 - Invalid quantity value, must be less than 4294967296 and greater than or equal to -1"

I'm passing my token too, I upload image for more details. 

![testingapi](https://cloud.githubusercontent.com/assets/18112657/24532031/2c17fd76-158b-11e7-99f5-80219d69c04b.jpg)

**Comment by sidhujag** [comment]
Try passing qty as string

**Comment by nlbi21** [comment]
`"quantity": "10",`

Error:

> Error: Parameter (request) failed schema validation
    at throwErrorWithCode (/home/ubuntu/syscoin-api/server/nodejs/node_modules/swagger-tools/lib/validators.js:121:13)
    at Object.module.exports.validateAgainstSchema (/home/ubuntu/syscoin-api/server/nodejs/node_modules/swagger-tools/lib/validators.js:176:7)
    at /home/ubuntu/syscoin-api/server/nodejs/node_modules/swagger-tools/middleware/swagger-validator.js:143:22
    at /home/ubuntu/syscoin-api/server/nodejs/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/home/ubuntu/syscoin-api/server/nodejs/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/home/ubuntu/syscoin-api/server/nodejs/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/ubuntu/syscoin-api/server/nodejs/node_modules/async/lib/async.js:337:20)
    at validateValue (/home/ubuntu/syscoin-api/server/nodejs/node_modules/swagger-tools/middleware/swagger-validator.js:136:11)
    at /home/ubuntu/syscoin-api/server/nodejs/node_modules/swagger-tools/middleware/swagger-validator.js:343:21
    at /home/ubuntu/syscoin-api/server/nodejs/node_modules/async/lib/async.js:356:13

**Comment by dwasyluk** [comment]
This looks legit, thanks for reporting it! I have all the info I need from the attached images. This will be a quick fix, I can have it remedied by tomorrow morning if not later tonight 👍

**Comment by nlbi21** [comment]
@dwasyluk nice man, I'll wait for your answer, thank you.

**Comment by dwasyluk** [comment]
@nlbi21 this is now fixed on the [dev 1.0.1 branch](https://github.com/syscoin/syscoin-api/tree/dev_1.0.1), I'll close the issue once the code is merged to master.

**Comment by nlbi21** [comment]
@dwasyluk Thanks man, I just tried it and everything works fine.

**Comment by dwasyluk** [comment]
@nlbi21 👍  thanks for confirming the fix. The unit tests are revealing a few more similarly-failing endpoints many of which are now fixed. I should have this "sanity test" level of unit tests completed tonight after which I'll tag/release 1.0.1, merge to master and close this issue officially.

**Comment by nlbi21** [comment]
@dwasyluk No problem man thank you too, the API also responds with a strange array, in the documentation it only comes out that responds with a "message". But the message brings something like this ["717f4d2cbf086436dfa6c320a8786a922027fa3be5b677deb4db21715cc96faa","0a05a8e277609b43"] It is normal? What does that message mean?

**Comment by dwasyluk** [comment]
@nlbi21 so the response doc/description in that regard could definitely be clearer, but what you're getting in the response is indeed correct. The response array contains 2 values- index 0 is the tx id of the offernew tx and index 1 is the GUID of the new offer. 

This is a common return pattern for almost all Syscoin endpoints that _create_ or _edit_ services-  they return an array consisting of 1 or 2 values. New operations will return 2 values [txid, guid], update operations will return an array with 1 value [txid].

I think it would be best to capture this response type as a concrete type so that the documentation can clearly express the above information in a more developer friendly way. Adding it to my list for v1.0.1 👍 .
